### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by Ajinkz** [bhavaniravi/rasa-site-bot#13]
which version of python did you used ? 2.x.x or 3.x.x ?

**Comment by mayurkadampro** [comment]
> which version of python did you used? 2.x.x or 3.x.x ?

its work in bot python2 as well python3 
but when you run app.py in python2 the error will appear for a urllib.parser module not found 
so if you want to run in python2 then simply change urllib.parser to urllib3
in case of python3 there is no error work perfectly
it's work fine for me

**Comment by Gowthamtriton** [comment]
Traceback (most recent call last):
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gowtham/PycharmProjects/site-bot/bot/app.py", line 63, in chat
    response_text = get_random_response(intent)
  File "/home/gowtham/PycharmProjects/site-bot/bot/app.py", line 20, in get_random_response
    print (response[intent])
KeyError: None
*********************************************
I got this kind of errors while I running ui and data trains perfectly

**Comment by Gowthamtriton** [comment]
Traceback (most recent call last):
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gowtham/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/gowtham/PycharmProjects/site-bot/bot/app.py", line 63, in chat
    response_text = get_random_response(intent)
  File "/home/gowtham/PycharmProjects/site-bot/bot/app.py", line 20, in get_random_response
    print (response[intent])
KeyError: None
***
I got this kind of errors while running UI and data trains perfectly then Iam using Ubuntu os
