### ISSUE TITLE
ImportError: No module named 'version'

### ISSUE THREAD

**Issue by sts77** [bhavaniravi/rasa-site-bot#14]
when i tried the training, got an import error :

python -m rasa_nlu.train -c AI-engine/config_spacy.json --data AI-engine/data/sitebot-data.json
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/sysg/.virtualenvs/rasa/lib/python3.5/site-packages/rasa_nlu/__init__.py", line 5, in <module>
    import version
ImportError: No module named 'version'

How to get rid of this error ?

**Comment by sts77** [comment]
when I used Python 3.6 no such error is encountered.
